### ISSUE TITLE
feat: donation amounts settings panel

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#20] opened 2019-09-12 20:58 UTC
# Feature Request

## User Story

As an admin, I want to manage donation amounts settings so that I can easily and visually create a campaign.

## Visuals

https://drive.google.com/open?id=1lsI_WRmOiKiS0VIcxmb5f-rgRA2VCVGQ

![image](https://user-images.githubusercontent.com/1784821/68921182-d9967e80-079d-11ea-974e-c7ce1a32449e.png)

## Possible Solution

Donation amounts settings should include: 
- Supporting text
- Enable custom amounts
- Add/Edit/Remove amounts

## Related

feat: campaign editor settings sidebar #17 

## Acceptance Criteria

- [x] Panel contains the settings listed above
- [x] Panel can be included in the settings sidebar
- [ ] <s>Panel settings changes are reflected in the preview</s>

**Comment by ravinderk** [comment] 2019-11-20 16:26
I am facing a Google Chrome specific issue with `react-dnd`: https://github.com/react-dnd/react-dnd/issues/1608

Moving this to the `Blocker` pipeline for now.

**Comment by DevinWalker** [comment] 2019-11-21 08:13
@ravinderk I am unable to reproduce that issue: https://www.loom.com/share/7635b446f7e24041a52b786561f345ec

**Comment by ravinderk** [comment] 2019-11-21 17:41
As per discussion, I was suggested by @kevinwhoffman to use `react-beautiful-dnd` by I misunderstood. I will tale care of `react-beautiful-dnd` integration.

ref: https://givewp.slack.com/archives/C0FAGC83C/p1574322811121600

**Comment by ravinderk** [comment] 2019-11-21 19:55
Update `Acceptance Criteria` because showing setting preview is out of scope until we finalize storing system/logic

**Closed** 2019-12-09 16:24 UTC
